server:
  port: 7171
spring:
  profiles:
    active: native
  application:
    name: SPRING-GATEWAY
  devtools:
    livereload:
      enabled: true
  cloud:
    gateway:
      routes:
      - id: ORGANIZATION
        uri: lb://ORGANIZATION
        predicates:
          - Path=/api/v1/organization/**
      - id: EMPLOYEE
        uri: lb://EMPLOYEE
        predicates:
          - Path=/api/v1/employee/**
      - id: ATTENDANCE 
        uri: lb://ATTENDANCE
        predicates:
          - Path=/api/v1/attendance/**
      - id: USER 
        uri: lb://USER
        predicates:
          - Path=/api/v1/user/**
      - id: FILE 
        uri: lb://FILE
        predicates:
          - Path=/api/v1/file/**
      - id: AUTH 
        uri: lb://AUTH
        predicates:
          - Path=/api/v1/auth/**